//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.10
//
// <auto-generated>
//
// Generated from file `ImageProcessor.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package ImageProcessing;

import com.zeroc.Ice.Current;

/** @hidden */
public abstract class _ImageProcessorPrxI extends com.zeroc.Ice._ObjectPrxI implements ImageProcessorPrx
{
    /** @hidden */
    public static final long serialVersionUID = 0L;

    public abstract byte[] Color2BW(byte[] colorImage, Current current);
}
